[window]
decorations = "None"
padding = { x = 3, y = 3 }

[scrolling]
history = 100000

[font]
normal = { family = "Terminus", style = "Regular" }
size = 10.0
offset = { x = 0, y = 0 }

[terminal]
shell = "nu"
