name: check
on: push

jobs:
  # Ensure .nix files are formatted.
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: install nix
        uses: DeterminateSystems/nix-installer-action@v20

      - run: nix run nixpkgs#nixfmt-tree -- --ci
