name: check
on: push

jobs:
  # Ensure .nix files are formatted.
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install nix
        uses: DeterminateSystems/nix-installer-action@v20

      - name: setup magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: nix run nixpkgs#nixfmt-tree -- --ci

  # Build rostam flake to check integrity
  build-rostam:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install nix
        uses: DeterminateSystems/nix-installer-action@v20

      - name: setup magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: build rostam configuration
        run: nix build ./hosts/rostam#nixosConfigurations.rostam.config.system.build.toplevel --print-build-logs
