name: check
on: push

jobs:
  # Ensure .nix files are formatted.
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install nix
        uses: DeterminateSystems/nix-installer-action@v20

      - name: install nixfmt
        run: nix profile add nixpkgs#nixfmt-tree

      - run: nixfmt-tree --check .
